[package]
name = "blink-led"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m-rt = "0.6.10"
cortex-m-semihosting = "0.3.3"
panic-halt = "0.2.0"
panic-semihosting = "0.6.0"

[dependencies.stm32f4]
version = "0.15.1"
features = ["stm32f411"]

